force-app/main/default/objects/Hotel_Master__c/Hotel_Master__c.object-meta.xml
<CustomObject>
    <label>Hotel Master</label>
    <nameField>
        <displayFormat>H-{000}</displayFormat>
        <label>Hotel Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Master__c/fields/Cancellation_Availability__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancellation Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/Cash_Pay_Availability__c.field-meta.xml
<CustomField>
    <fullName>Cash_Pay_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cash Pay Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/Hotel_City__c.field-meta.xml
<CustomField>
    <fullName>Hotel_City__c</fullName>
    <label>Hotel City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <label>Hotel Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/Hotel_Type__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Type__c</fullName>
    <label>Hotel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Star</fullName>
            </value>
            <value>
                <fullName>4 Star</fullName>
            </value>
            <value>
                <fullName>5 Star</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/Per_Day_Cost__c.field-meta.xml
<CustomField>
    <fullName>Per_Day_Cost__c</fullName>
    <label>Per Day Cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hotel_Master__c/fields/WiFi_Availability__c.field-meta.xml
<CustomField>
    <fullName>WiFi_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WiFi Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GetHotelsList.cls
public with sharing class GetHotelsList {
    @AuraEnabled (Cacheable=true)
    public static List<Hotel_Master__c> getHotels(String city){
        System.debug('city is' + city);
        String key = '%' + city + '%' ;
        return [SELECT Id,Hotel_Name__c,	Hotel_Type__c, 	Per_Day_Cost__c,
                    WiFi_Availability__c,Hotel_City__c,Cash_Pay_Availability__c,Cancellation_Availability__c
                     FROM Hotel_Master__c WHERE Hotel_City__c LIKE : key];

    }
}