force-app/main/default/objects/Guest_Master__c/Guest_Master__c.object-meta.xml
<CustomObject>
    <label>Guest Master</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>Guest Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guest Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Master__c/Payment_Master__c.object-meta.xml
<CustomObject>
    <label>Payment Master</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Masters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Master__c/fields/CVV__c.field-meta.xml
<CustomField>
    <fullName>CVV__c</fullName>
    <label>CVV</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Master__c/fields/Guest_Master__c.field-meta.xml
<CustomField>
    <fullName>Guest_Master__c</fullName>
    <label>Guest Master</label>
    <referenceTo>Guest_Master__c</referenceTo>
    <relationshipLabel>Payment Masters</relationshipLabel>
    <relationshipName>Payment_Masters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SavePaymentDetails.cls
public with sharing class SavePaymentDetails {
    @AuraEnabled
    public static Payment_Master__c SavePaymentDetailsNow(Id recordId, Integer cardNumber, Integer cardExpiryMonth, Integer cardExpiryYear, Integer cardCvv) {

        System.debug(recordId);
        System.debug(cardNumber);
        System.debug(cardExpiryMonth);
        System.debug(cardExpiryYear);
        System.debug(cardCvv);

        Payment_Master__c p = new Payment_Master__c();
        p.Guest_Master__c = recordId;
        p.Card_Number__c = cardNumber;
        p.Expiry_Month__c = cardExpiryMonth;
        p.Expiry_Year__c = cardExpiryYear;
        p.CVV__c = cardCvv;

        try {
            insert p;
           System.debug('successfully inserted');
        } catch (Exception e) {
            System.debug('Failed to get inserted');
            system.debug(e.getMessage());


        }

        return p;

    }
}