force-app/main/default/objects/Guest_Master__c/Guest_Master__c.object-meta.xml
<CustomObject>
    <label>Guest Master</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>Guest Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guest Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guest_Master__c/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <label>Guest First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guest_Master__c/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <label>Guest Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guest_Master__c/fields/Guest_Phone__c.field-meta.xml
<CustomField>
    <fullName>Guest_Phone__c</fullName>
    <label>Guest Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SaveGuestInformation.cls
public with sharing class SaveGuestInformation {
    @AuraEnabled
    public static Guest_Master__c SaveGuest(String firstName, String lastName, String phone, String email) {
        System.debug(firstName);
        System.debug(lastName);
        System.debug(email);
        System.debug(phone);

        Guest_Master__c g = new Guest_Master__c();
        g.Guest_First_Name__c = firstName;
        g.Guest_Last_Name__c =lastName;
        g.Guest_Phone__c = phone;
        g.Guest_Email__c = email;
        try {
            insert g;
        } catch (Exception e) {
            system.debug(e.getMessage());

        }

        return g;

    }
}